name: entity-env
channels:
    - defaults
    - anaconda
    - conda-forge
dependencies:
  - beautifulsoup4==4.8.1
  - flask==1.1.1
  - ipykernel==5.1.4
  - jupyter==6.0.3
  - matplotlib==3.1.3
  - numpy==1.18.1
  - pandas==1.0.1
  - python==3.7
  - requests==2.23.0
  - spacy==2.2.3
  - spacy-model-en_core_web_sm==2.2.5
